name: catatankeuangan
description: "A new Flutter project."


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: '>=3.5.3 <=4.0.0'







dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.2
  cupertino_icons: ^1.0.2
  intl: ^0.19.0


  
  

dev_dependencies:
  flutter_test:
    sdk: flutter


  
  
  
  
  
  flutter_slidable: ^3.0.1
  auto_size_text: ^3.0.0
  line_awesome_flutter: ^2.0.0
  my_app: ^1.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10
  build_runner: ^2.4.8


flutter_native_splash:
  
  image: assets/logo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21
 
  





flutter:

  
  
  
  uses-material-design: true

  
  assets:
    - assets/

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
